<?php

namespace Tests;

use PHPUnit\Framework\TestCase;
use Aptenex\Upp\Util\AvailabilityUtils;

class AvailabilityUtilsTest extends TestCase
{

    public function testExtractRanges(): void
    {
        $set = [
            'startDatum' => '2019-08-01',
            'sequence' => 'YNNNNNNNNNNNNNNNNNNYYNNNNNNNNNNYYNNNNNYYYYYYYYYYYYYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN'
        ];

        /**
         * @var \DateTime $startDate
         * @var string[] $ranges
         */
        [$startDate, $ranges] = AvailabilityUtils::extractRanges($set);

        $expectedRanges = [
            'Y',
            'NNNNNNNNNNNNNNNNNN',
            'YY',
            'NNNNNNNNNN',
            'YY',
            'NNNNN',
            'YYYYYYYYYYYYYY',
            'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
            'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
            'NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
        ];

        $this->assertSame('2019-08-01', $startDate->format('Y-m-d'));
        $this->assertSame($expectedRanges, $ranges);
    }

    public function testGetAvailabilityRangesIncludingState(): void
    {
        $set = [
            'startDatum' => '2019-08-01',
            'sequence' => 'YNNNNNNNNNNNNNNNNNNYYNNNNNNNNNNYYNNNNNYYYYYYYYYYYYYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNYYYYYYYYYYYYYYYNYNYNYNYNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNY'
        ];

        $expectedRanges = '[{"startDate":"2019-08-01 10:00:00","endDate":"2019-08-01 14:00:00","type":"Y"},{"startDate":"2019-08-02 14:00:00","endDate":"2019-08-19 10:00:00","type":"N"},{"startDate":"2019-08-20 14:00:00","endDate":"2019-08-21 10:00:00","type":"Y"},{"startDate":"2019-08-22 14:00:00","endDate":"2019-08-31 10:00:00","type":"N"},{"startDate":"2019-09-01 14:00:00","endDate":"2019-09-02 10:00:00","type":"Y"},{"startDate":"2019-09-03 14:00:00","endDate":"2019-09-07 10:00:00","type":"N"},{"startDate":"2019-09-08 14:00:00","endDate":"2019-09-21 10:00:00","type":"Y"},{"startDate":"2019-09-22 14:00:00","endDate":"2019-10-28 10:00:00","type":"N"},{"startDate":"2019-10-29 14:00:00","endDate":"2019-11-12 10:00:00","type":"Y"},{"startDate":"2019-11-13 10:00:00","endDate":"2019-11-13 14:00:00","type":"N"},{"startDate":"2019-11-14 10:00:00","endDate":"2019-11-14 14:00:00","type":"Y"},{"startDate":"2019-11-15 10:00:00","endDate":"2019-11-15 14:00:00","type":"N"},{"startDate":"2019-11-16 10:00:00","endDate":"2019-11-16 14:00:00","type":"Y"},{"startDate":"2019-11-17 10:00:00","endDate":"2019-11-17 14:00:00","type":"N"},{"startDate":"2019-11-18 10:00:00","endDate":"2019-11-18 14:00:00","type":"Y"},{"startDate":"2019-11-19 10:00:00","endDate":"2019-11-19 14:00:00","type":"N"},{"startDate":"2019-11-20 10:00:00","endDate":"2019-11-20 14:00:00","type":"Y"},{"startDate":"2019-11-21 10:00:00","endDate":"2019-11-21 14:00:00","type":"N"},{"startDate":"2019-11-22 14:00:00","endDate":"2021-03-31 10:00:00","type":"Y"},{"startDate":"2021-04-01 14:00:00","endDate":"2022-07-30 10:00:00","type":"N"},{"startDate":"2022-07-31 10:00:00","endDate":"2022-07-31 14:00:00","type":"Y"}]';

        $result = AvailabilityUtils::getAvailabilityRangesIncludingState($set, true);

        $this->assertSame(json_encode(json_decode($expectedRanges, true), JSON_PRETTY_PRINT), json_encode($result, JSON_PRETTY_PRINT));
    }

}